#! /bin/sh

# Make sure we are in the directory of this script
cd "$(dirname "$(realpath "$0")")";

# Move up to project root 
cd ../../

echo "[BUILDING IMAGE]\n";
docker build --tag muzero-env-2021:v1.0 -f env/cpu/Dockerfile . > /dev/null

echo "\n[STARTING CONTAINER]\n";

docker network create muzero-net

if docker ps | grep -q "muzero-lab";
then 
    echo "...already running"; 
else 
    # Start container
    docker run --rm -p 8888:8888 -p 6006:6006 -p 6005:6005 \
      -e JUPYTER_ENABLE_LAB=yes \
      -v "$PWD/../":/home/jovyan/working \
      --name muzero-lab \
      --net muzero-net \
      --gpus all \
      -d \
      muzero-env-2021:v1.0

    # Wait for container to start up
    while ! docker logs muzero-lab 2>&1 | grep "token" 
    do
      echo "..."
      sleep 1;
    done
    echo "...started"; 
fi

if docker ps | grep -q "muzero-redis";
then 
    echo "...db already running"; 
else 
    # Start container
    docker run --rm -p 6379:6379 \
      --name muzero-redis \
      --net muzero-net \
      -v $PWD/data:/data \
      -d \
      redis redis-server --save 60 1 --loglevel warning
fi

TOKEN=$(docker logs muzero-lab 2>&1 | egrep -o -m 1 'token=\w+');

while getopts ":o" opt; do
  case ${opt} in
    o )
        echo "...opening in browser"; 
        python -m webbrowser http://localhost:8888?$TOKEN
      ;;
    \? )
      ;;
  esac
done

echo "...visit: http://localhost:8888?$TOKEN\n";
