#! /bin/sh

# Make sure we are in the directory of this script
cd "$(dirname "$(realpath "$0")")";

echo "[BUILDING IMAGE]\n";
docker build --tag ebay-ml-2021:v1.0 .

# Move up to project root 
cd ../..

echo "\n[STARTING CONTAINER]\n";

docker network create ebay-ml-net
docker volume create ebay-ml-db-data

if docker ps | grep -q "ebay-ml-lab";
then 
    echo "...already running"; 
else 
    # Start container
    docker run --rm -p 8888:8888 \
      -e JUPYTER_ENABLE_LAB=yes \
      -e GRANT_SUDO=yes \
      -v "$PWD":/home/jovyan/working \
      --name ebay-ml-lab \
      --net ebay-ml-net \
      --gpus all \
      -d \
      ebay-ml-2021:v1.0

    docker logs ebay-ml-lab
    # Wait for container to start up
    #while ! docker logs ebay-ml-lab 2>&1 | grep "token" 
    #do
    #  echo "..."
    #  sleep 1;
    #done
    echo "...started"; 
fi

TOKEN=$(docker logs ebay-ml-lab 2>&1 | egrep -o -m 1 'token=\w+');

while getopts ":o" opt; do
  case ${opt} in
    o )
        echo "...opening in browser"; 
        python -m webbrowser http://localhost:8888?$TOKEN
      ;;
    \? )
      ;;
  esac
done

echo "...visit: http://localhost:8888?$TOKEN\n";
